### PR TITLE
SPP

### PR DESCRIPTION
**Pull request by alexbarrera**
Added Dockerfile and libraries for the SPP R program.

### CODE REVIEW

**Comment by alexbarrera** [comment]
@dleehr could you please have a look and possibly build the image under dukegcb/spp? I'm planning to submit the tool to https://github.com/common-workflow-language/workflows, but since I will be including the DockerImage in the submission it would make sense if the tool Docker image is already published.

**Comment by dleehr** [comment]
Sure thing

**Comment by alexbarrera** [comment]
Thanks Dan. I noticed that there was an [error building the Dockerfile](https://hub.docker.com/r/dukegcb/spp/builds/bdep7a8c7dleh3wy6rszcan/). I guess you are looking into this. Would you mind letting me know when the build works? I have [this branch](https://github.com/alexbarrera/workflows/tree/spp-tool) ready for PR, but I would wait until the image is properly built. Thanks!

**Comment by dleehr** [comment]
@alexbarrera I've tried to rebuild this twice, it keeps failing: https://hub.docker.com/r/dukegcb/spp/builds/bsgnk9y3tew8nlmbeqb87ah/

**Comment by alexbarrera** [comment]
@dleehr Have you managed to build it in a local machine? I don't have any problems with it.

**Comment by dleehr** [comment]
Fails at the same place for me:

```
/usr/include/c++/5/cmath:926:3: error: template with C linkage
   template<typename _Tp>
   ^
/usr/include/c++/5/cmath:935:3: error: template with C linkage
   template<typename _Tp>
   ^
/usr/lib/R/etc/Makeconf:141: recipe for target 'bed2vector.o' failed
make: *** [bed2vector.o] Error 1
ERROR: compilation failed for package ‘spp’
* removing ‘/usr/local/lib/R/site-library/spp’
The command '/bin/sh -c printf 'source("https://bioconductor.org/biocLite.R")\nbiocLite("Rsamtools")\n' > install_Rsamtools.R &&     Rscript install_Rsamtools.R &&     curl -SLo ./spp_${SPP_VERSION}.tar.gz https://github.com/hms-dbmi/spp/archive/${SPP_VERSION}.tar.gz &&     curl -SLo ./bitops_1.0-6.tar.gz https://cran.r-project.org/src/contrib/bitops_1.0-6.tar.gz &&     curl -SLo ./caTools_1.17.1.tar.gz https://cran.r-project.org/src/contrib/caTools_1.17.1.tar.gz &&     R CMD INSTALL bitops_1.0-6.tar.gz &&     R CMD INSTALL caTools_1.17.1.tar.gz &&     R CMD INSTALL spp_${SPP_VERSION}.tar.gz &&     rm -f ./spp_${SPP_VERSION}.tar.gz ./bitops_1.0-6.tar.gz ./caTools_1.17.1.tar.gz ./install_Rsamtools.R' returned a non-zero code: 1
```

Have you pulled `r-base:latest` lately?

**Comment by alexbarrera** [comment]
> Have you pulled r-base:latest lately?
No, I have not. My `r-base:latest` image was created 3 months ago. I just retagged and pull the most recent `r-base:latest` and I got the same error. 

I have reverted the r-base image to the 3.2.4 version and that fix the problem. Would you mind to change the SPP Dockerfile and try to build it again? Thanks!

**Comment by dleehr** [comment]
@alexbarrera OK I changed the Dockerfile to specify 3.2.4 and it builds now

**Pull request merged**
